// Full positive interpretations of the 22 arcana for the decode section.
// Tone: professional but warm; entertainment format, no fatalism.
import type { L } from './library';

export interface ArcanaText { long: L; plus: L; growth: L; tip: L }

export const arcanaTexts: Record<number, ArcanaText> = {
  1: { long: { ru: 'Энергия воли и начала. Этот аркан даёт умение превращать идею в первый шаг, брать инициативу и вести за собой. Его сила — в концентрации: одно ясное намерение здесь стоит десяти планов.', en: 'The energy of will and beginnings. This arcana turns ideas into first steps, takes initiative and leads. Its power is focus: one clear intention here is worth ten plans.' }, plus: { ru: 'инициатива, лидерство, скорость решений', en: 'initiative, leadership, quick decisions' }, growth: { ru: 'доводить начатое до устойчивого результата', en: 'carrying what you start through to a stable result' }, tip: { ru: 'Начинайте день с одного важного действия — импульс сделает остальное.', en: 'Start the day with one important action — momentum will do the rest.' } },
  2: { long: { ru: 'Энергия интуиции и глубокого знания. Аркан тонкого чувствования: он помогает слышать недосказанное, понимать людей и хранить чужие тайны бережно.', en: 'The energy of intuition and deep knowing. An arcana of subtle perception: it helps you hear the unsaid, understand people and keep confidences with care.' }, plus: { ru: 'эмпатия, глубина, умение слышать', en: 'empathy, depth, true listening' }, growth: { ru: 'доверять своим ощущениям и озвучивать их', en: 'trusting your inner signals and voicing them' }, tip: { ru: 'Записывайте догадки — они чаще верны, чем кажется.', en: 'Write down your hunches — they are right more often than it seems.' } },
  3: { long: { ru: 'Энергия изобилия и созидания. Этот аркан любит красоту, заботу и рост: всё, к чему он прикасается, расцветает — проекты, отношения, пространство.', en: 'The energy of abundance and creation. This arcana loves beauty, care and growth: whatever it touches blossoms — projects, relationships, spaces.' }, plus: { ru: 'творческая энергия, щедрость, вкус', en: 'creative energy, generosity, taste' }, growth: { ru: 'разрешать себе создавать без оценки', en: 'allowing yourself to create without judging' }, tip: { ru: 'Выделяйте час в неделю на творчество без цели и результата.', en: 'Set aside one hour a week for creating with no goal at all.' } },
  4: { long: { ru: 'Энергия структуры и ответственности. Аркан строителя: он превращает хаос в систему, мечты в планы и даёт окружающим ощущение надёжной опоры.', en: 'The energy of structure and responsibility. The builder’s arcana: it turns chaos into systems, dreams into plans, and gives others a sense of solid ground.' }, plus: { ru: 'системность, надёжность, управление', en: 'organisation, reliability, management' }, growth: { ru: 'оставлять место мягкости внутри строгих планов', en: 'leaving room for softness inside strict plans' }, tip: { ru: 'Планируйте отдых так же серьёзно, как дела.', en: 'Schedule rest as seriously as work.' } },
  5: { long: { ru: 'Энергия знания и традиции. Аркан наставника: учиться, осмыслять и передавать дальше. Его глубина превращает опыт в мудрость, а мудрость — в поддержку для других.', en: 'The energy of knowledge and tradition. The mentor’s arcana: to learn, make sense and pass on. Its depth turns experience into wisdom, and wisdom into support for others.' }, plus: { ru: 'мудрость, умение объяснять, уважение к опыту', en: 'wisdom, teaching, respect for experience' }, growth: { ru: 'оставаться открытым новому, не только проверенному', en: 'staying open to the new, not only the proven' }, tip: { ru: 'Поделитесь знанием с одним человеком на этой неделе.', en: 'Share one piece of knowledge with one person this week.' } },
  6: { long: { ru: 'Энергия любви и выбора сердцем. Этот аркан строит мосты между людьми: партнёрство, дружбу, тёплые союзы. Его сила — искренность.', en: 'The energy of love and heart-made choices. This arcana builds bridges between people: partnership, friendship, warm alliances. Its power is sincerity.' }, plus: { ru: 'тепло, верность, дар объединять', en: 'warmth, loyalty, the gift of uniting' }, growth: { ru: 'выбирать себя так же бережно, как других', en: 'choosing yourself as kindly as you choose others' }, tip: { ru: 'Скажите близкому человеку, за что вы его цените.', en: 'Tell someone close what you value in them.' } },
  7: { long: { ru: 'Энергия движения и победы. Аркан колесницы: воля, собранность и умение держать курс. Препятствия для него — разметка дороги, а не стена.', en: 'The energy of motion and victory. The chariot’s arcana: will, composure and staying on course. Obstacles are road markings to it, not walls.' }, plus: { ru: 'целеустремлённость, самодисциплина, драйв', en: 'determination, self-discipline, drive' }, growth: { ru: 'делать паузы, чтобы направление оставалось вашим', en: 'pausing so the direction stays truly yours' }, tip: { ru: 'Сформулируйте цель недели одной фразой и держите её на виду.', en: 'Put this week’s goal into one sentence and keep it visible.' } },
  8: { long: { ru: 'Энергия справедливости и равновесия. Этот аркан видит причины и следствия, умеет говорить правду бережно и выравнивать то, что накренилось.', en: 'The energy of justice and balance. This arcana sees cause and effect, tells the truth kindly and levels what has tilted.' }, plus: { ru: 'честность, ясность, чувство меры', en: 'honesty, clarity, a sense of measure' }, growth: { ru: 'быть к себе так же справедливым, как к другим', en: 'being as fair to yourself as to others' }, tip: { ru: 'Принимая решение, спросите: «А как здесь будет честно по отношению ко мне?»', en: 'When deciding, ask: “What would be fair to me here?”' } },
  9: { long: { ru: 'Энергия мудрости и внутреннего света. Аркан отшельника: умение побыть в тишине, найти свой ответ и вернуться к людям с фонарём, а не с усталостью.', en: 'The energy of wisdom and inner light. The hermit’s arcana: the ability to be still, find your own answer and return to people with a lantern, not with weariness.' }, plus: { ru: 'глубина, самодостаточность, проницательность', en: 'depth, self-sufficiency, insight' }, growth: { ru: 'делиться выводами, а не только вынашивать их', en: 'sharing conclusions, not only incubating them' }, tip: { ru: 'Планируйте небольшие паузы тишины — это ваша подзарядка.', en: 'Plan small pockets of silence — that is how you recharge.' } },
  10: { long: { ru: 'Энергия удачи и циклов. Этот аркан чувствует момент: когда сделать шаг, когда подождать. Жизнь любит предлагать ему счастливые повороты — важно лишь замечать их.', en: 'The energy of fortune and cycles. This arcana senses timing: when to step and when to wait. Life loves offering it lucky turns — one only needs to notice them.' }, plus: { ru: 'чувство момента, адаптивность, оптимизм', en: 'timing, adaptability, optimism' }, growth: { ru: 'опираться и на систему, а не только на волну', en: 'leaning on systems too, not only on the wave' }, tip: { ru: 'Замечайте одно «удачное совпадение» в день — их больше, чем кажется.', en: 'Notice one “lucky coincidence” a day — there are more than you think.' } },
  11: { long: { ru: 'Энергия мягкой силы. Аркан укротителя: не ломать, а приручать; не давить, а выдерживать. Спокойная устойчивость этого аркана сильнее любого нажима.', en: 'The energy of gentle strength. The tamer’s arcana: not to break but to tame, not to push but to endure. Its calm steadiness is stronger than any force.' }, plus: { ru: 'выдержка, храбрость, внутренний стержень', en: 'endurance, courage, an inner core' }, growth: { ru: 'позволять себе просить поддержку', en: 'allowing yourself to ask for support' }, tip: { ru: 'В напряжённый момент — три медленных выдоха, затем ответ.', en: 'In a tense moment: three slow exhales, then respond.' } },
  12: { long: { ru: 'Энергия нового взгляда. Этот аркан умеет перевернуть привычную картинку и увидеть решение там, где другие видят тупик. Пауза для него — рабочий инструмент.', en: 'The energy of a fresh perspective. This arcana flips the familiar picture and sees solutions where others see dead ends. Pause is its working tool.' }, plus: { ru: 'нестандартное мышление, терпение, творческие решения', en: 'unconventional thinking, patience, creative solutions' }, growth: { ru: 'возвращаться из раздумий к действию', en: 'returning from reflection to action' }, tip: { ru: 'Застряли? Опишите задачу с точки зрения другого человека.', en: 'Stuck? Describe the task from another person’s point of view.' } },
  13: { long: { ru: 'Энергия обновления. Аркан трансформации: бережно завершать отжившее и освобождать место новому. Каждое его «прощай» — на самом деле «здравствуй».', en: 'The energy of renewal. The arcana of transformation: gently closing what has expired and making room for the new. Each of its goodbyes is truly a hello.' }, plus: { ru: 'смелость перемен, лёгкость отпускания, живучесть', en: 'courage to change, ease of letting go, resilience' }, growth: { ru: 'завершать циклы с благодарностью, без спешки', en: 'closing cycles with gratitude, without haste' }, tip: { ru: 'Раз в месяц отпускайте одну вещь, привычку или задачу.', en: 'Once a month release one object, habit or task.' } },
  14: { long: { ru: 'Энергия меры и гармонии. Аркан алхимика: смешивать противоположности в правильных пропорциях — работу и отдых, чувство и разум, своё и чужое.', en: 'The energy of measure and harmony. The alchemist’s arcana: blending opposites in the right proportions — work and rest, feeling and reason, yours and theirs.' }, plus: { ru: 'дипломатичность, чувство баланса, исцеляющее спокойствие', en: 'diplomacy, a sense of balance, healing calm' }, growth: { ru: 'защищать свой ритм от чужой спешки', en: 'protecting your rhythm from other people’s haste' }, tip: { ru: 'Проверяйте баланс недели: что добавить, что убавить.', en: 'Audit the week’s balance: what to add, what to reduce.' } },
  15: { long: { ru: 'Энергия магнетизма и жизненной силы. Этот аркан — про харизму, страсть к жизни и умение притягивать людей и ресурсы. В зрелом виде это большая творческая мощь.', en: 'The energy of magnetism and vitality. This arcana is about charisma, passion for life and the power to attract people and resources. Matured, it is great creative force.' }, plus: { ru: 'харизма, энергичность, влияние', en: 'charisma, vitality, influence' }, growth: { ru: 'направлять притяжение на то, что действительно ваше', en: 'aiming your magnetism at what is truly yours' }, tip: { ru: 'Замечайте, что даёт вам энергию, а что только возбуждение.', en: 'Notice what gives you energy versus mere excitement.' } },
  16: { long: { ru: 'Энергия освобождения. Аркан выхода из тесных рамок: там, где рушится старое, у этого аркана открывается небо. Он умеет начинать заново — легче и честнее.', en: 'The energy of liberation. The arcana of leaving tight frames: where the old falls away, this arcana finds open sky. It knows how to begin again — lighter and truer.' }, plus: { ru: 'смелость, честность с собой, быстрая перезагрузка', en: 'boldness, self-honesty, fast reset' }, growth: { ru: 'обновлять по кирпичику, не дожидаясь бури', en: 'renewing brick by brick, without waiting for a storm' }, tip: { ru: 'Меняйте маленькое сразу, как только почувствовали тесноту.', en: 'Change something small as soon as things feel tight.' } },
  17: { long: { ru: 'Энергия надежды и вдохновения. Аркан звезды: видеть свет даже издалека и зажигать его в других. Мечты этого аркана — не бегство, а навигация.', en: 'The energy of hope and inspiration. The star’s arcana: seeing light even from afar and kindling it in others. Its dreams are navigation, not escape.' }, plus: { ru: 'вера, вдохновение, дар поддерживать', en: 'faith, inspiration, the gift of encouragement' }, growth: { ru: 'превращать мечты в маленькие конкретные шаги', en: 'turning dreams into small concrete steps' }, tip: { ru: 'Выберите одну мечту и сделайте для неё один шаг на этой неделе.', en: 'Pick one dream and take one step toward it this week.' } },
  18: { long: { ru: 'Энергия интуиции и воображения. Лунный аркан слышит тонкие подсказки, видит образы и настроения раньше слов. Это дар художников и тонких психологов.', en: 'The energy of intuition and imagination. The lunar arcana hears subtle hints and senses moods before words. It is the gift of artists and fine psychologists.' }, plus: { ru: 'чутьё, образное мышление, глубина чувств', en: 'instinct, imaginative thinking, emotional depth' }, growth: { ru: 'сверять образы с фактами — и доверять себе', en: 'checking images against facts — and trusting yourself' }, tip: { ru: 'Ведите вечером три строки о прожитом дне — интуиция любит внимание.', en: 'Write three lines about your day each evening — intuition loves attention.' } },
  19: { long: { ru: 'Энергия радости и света. Солнечный аркан согревает: рядом с ним люди распрямляются, дела ладятся, а день становится ярче. Его сила — искренняя радость жизни.', en: 'The energy of joy and light. The solar arcana warms: near it people straighten up, things click, days grow brighter. Its power is sincere joy of living.' }, plus: { ru: 'оптимизм, открытость, витальность', en: 'optimism, openness, vitality' }, growth: { ru: 'разрешать себе быть не только источником света, но и его получателем', en: 'allowing yourself to receive light, not only give it' }, tip: { ru: 'Делитесь радостью вслух — она умножается от произнесения.', en: 'Say your joys out loud — they multiply when spoken.' } },
  20: { long: { ru: 'Энергия пробуждения. Аркан осознанных выводов: слышать зов нового этапа и отвечать на него. Прошлое для него — учебник, а не якорь.', en: 'The energy of awakening. The arcana of conscious conclusions: hearing the call of a new stage and answering it. The past is its textbook, not an anchor.' }, plus: { ru: 'осознанность, зрелость, умение прощать', en: 'mindfulness, maturity, the ability to forgive' }, growth: { ru: 'принимать выводы без самокритики', en: 'drawing conclusions without self-criticism' }, tip: { ru: 'Спросите себя: «К чему меня зовёт этот период?»', en: 'Ask yourself: “What is this period calling me toward?”' } },
  21: { long: { ru: 'Энергия целостности и завершения. Аркан мира: собирать жизнь в цельную картину, где каждому опыту есть место. Это энергия успеха, признания и широких горизонтов.', en: 'The energy of wholeness and completion. The world’s arcana: gathering life into a whole picture where every experience has its place. It is the energy of success, recognition and wide horizons.' }, plus: { ru: 'целостность, широта взгляда, умение завершать красиво', en: 'wholeness, breadth of view, finishing beautifully' }, growth: { ru: 'праздновать достижения, а не сразу бежать дальше', en: 'celebrating achievements instead of rushing on' }, tip: { ru: 'Завершив дело, поставьте точку-ритуал: поблагодарите себя.', en: 'When something ends, mark it: thank yourself.' } },
  22: { long: { ru: 'Энергия свободы и доверия миру. Аркан безграничности: лёгкость первого шага, искренний интерес и вера, что дорога подскажет. Это вечная молодость души.', en: 'The energy of freedom and trust in the world. The arcana of boundlessness: the lightness of a first step, sincere curiosity and faith that the road will guide. It is the soul’s eternal youth.' }, plus: { ru: 'лёгкость, спонтанность, открытость чудесам', en: 'lightness, spontaneity, openness to wonder' }, growth: { ru: 'добавлять свободе немного маршрута', en: 'giving freedom a bit of a route' }, tip: { ru: 'Разрешите себе одно спонтанное приключение в неделю.', en: 'Allow yourself one spontaneous adventure a week.' } },
};

export const pairStrengthsPool: L[] = [
  { ru: 'Вы умеете слышать друг друга даже без слов', en: 'You can hear each other even without words' },
  { ru: 'Ваш союз соединяет мечтательность и практичность', en: 'Your union joins dreaminess and practicality' },
  { ru: 'Вместе вам легче решаться на новое', en: 'Together it is easier to dare something new' },
  { ru: 'Вы умеете превращать быт в заботу, а не рутину', en: 'You turn everyday life into care, not routine' },
  { ru: 'Ваши сильные стороны красиво дополняют друг друга', en: 'Your strengths complement each other beautifully' },
  { ru: 'Рядом друг с другом вы становитесь смелее', en: 'Next to each other you both grow braver' },
  { ru: 'У вашей пары общий источник вдохновения', en: 'Your pair shares one source of inspiration' },
];

export const pairTipsPool: L[] = [
  { ru: 'Заведите маленький общий ритуал — утренний кофе, вечернюю прогулку.', en: 'Create a small shared ritual — morning coffee, an evening walk.' },
  { ru: 'Раз в неделю говорите друг другу спасибо за что-то конкретное.', en: 'Once a week thank each other for something specific.' },
  { ru: 'Планируйте одно новое совместное впечатление в месяц.', en: 'Plan one new shared experience a month.' },
  { ru: 'Обсуждайте мечты, а не только дела — мечты сближают.', en: 'Discuss dreams, not only chores — dreams bring people closer.' },
  { ru: 'Давайте друг другу время на личную тишину без обид.', en: 'Give each other personal quiet time without offence.' },
  { ru: 'Отмечайте маленькие победы пары — они складываются в большую историю.', en: 'Celebrate the pair’s small wins — they add up to a big story.' },
];
